#
#
# 说明：
# 
# ‘删除在github空间的老固件’ 删除N小时前的固件，保留数设置没效，一删除就会把在删除时间段内的固件全部删除
#  一次编译一个机型的不会出问题，一次编译多个机型的会出现删除错误，不能继续编译了，所有只能把这两个删除独立出来
#
# ‘删除自动发布的老固件’ 每次启动都生效，可以设置保留数
#


name: delete-workflow-runs
on:
  workflow_dispatch:

#  schedule:
#    - cron: 0 8 */5 * *

jobs:
  del_runs:
    runs-on: Ubuntu-20.04
    name: delete-workflow-runs
    steps:
    
      - name: 删除在github空间的老固件
        uses: Mattraks/delete-workflow-runs@main
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}       
          retain_days: 0.1
          keep_minimum_runs: 0
    
      - name: 删除自动发布的老固件
        uses: dev-drprasad/delete-older-releases@v0.1.0
        with:
          keep_latest: 0         #保留多少个发布不删除
          delete_tags: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
